import { faker } from '@faker-js/faker';
import { sample } from 'lodash';

// ----------------------------------------------------------------------

const covidPositive = [...Array(110)].map((_, index) => ({
  sn: faker.datatype.number({
    min: 55555,
    max: 99999999,
  }).toString(),
  // date: faker.date.between('2020-01-01', '2021-12-30'),
  date: '2020-01-01',
  age: faker.datatype.number({
    min: 1,
    max: 80,
  }),
  sex: sample(['Male', 'Female']),
  province: sample([
    'Province 1',
    'Madhesh',
    'Bagmati',
    'Gandaki',
    'Province 5',
    'Karnali',
    'Sudurpaschim',
  ]),
  district: sample([
    'achham',
    'arghakhanchi',
    'baglung',
    'baitadi',
    'bajhang',
    'bajura',
    'banke',
    'bara',
    'bardiya',
    'bhaktapur',
    'bhojpur',
    'chitwan',
    'dadeldhura',
    'dailekh',
    'dang deukhuri',
    'darchula',
    'dhading',
    'dhankuta',
    'dhanusa',
    'dholkha',
    'dolpa',
    'doti',
    'gorkha',
    'gulmi',
    'humla',
    'ilam',
    'jajarkot',
    'jhapa',
    'jumla',
    'kailali',
    'kalikot',
    'kanchanpur',
    'kapilvastu',
    'kaski',
    'kathmandu',
    'kavrepalanchok',
    'khotang',
    'lalitpur',
    'lamjung',
    'mahottari',
    'makwanpur',
    'manang',
    'morang',
    'mugu',
    'mustang',
    'myagdi',
    'nawalparasi',
    'nuwakot',
    'okhaldhunga',
    'palpa',
    'panchthar',
    'parbat',
    'parsa',
    'pyuthan',
    'ramechhap',
    'rasuwa',
    'rautahat',
    'rolpa',
    'rukum',
    'rupandehi',
    'salyan',
    'sankhuwasabha',
    'saptari',
    'sarlahi',
    'sindhuli',
    'sindhupalchok',
    'siraha',
    'solukhumbu',
    'sunsari',
    'surkhet',
    'syangja',
    'tanahu',
    'taplejung',
    'terhathum',
    'udayapur',
  ]),
}));

export default covidPositive;
