import { faker } from '@faker-js/faker';
import { sample } from 'lodash';
import {fDate} from '../utils/formatTime';

// ----------------------------------------------------------------------

const covidDeath = [...Array(110)].map((_, index) => ({
  casenum: faker.datatype
    .number({
      min: 55555,
      max: 99999999,
    })
    .toString(),
  // date: faker.date.between('2020-01-01', '2021-12-30'),
  date_death: fDate(faker.date
    .between('2020-01-01', '2021-12-30')),
  date_positive: fDate(faker.date
    .between('2020-01-01', '2021-12-30')),
  age: faker.datatype.number({
    min: 1,
    max: 80,
  }),
  sex: sample(['Male', 'Female']),
  province: sample([
    'Province-1',
    'Madhesh',
    'Bagmati',
    'Gandaki',
    'Lumbini',
    'Karnali',
    'Sudurpaschim',
  ]),
  district: sample([
    'achham',
    'arghakhanchi',
    'baglung',
    'baitadi',
    'bajhang',
    'bajura',
    'banke',
    'bara',
    'bardiya',
    'bhaktapur',
    'bhojpur',
    'chitwan',
    'dadeldhura',
    'dailekh',
    'dang deukhuri',
    'darchula',
    'dhading',
    'dhankuta',
    'dhanusa',
    'dholkha',
    'dolpa',
    'doti',
    'gorkha',
    'gulmi',
    'humla',
    'ilam',
    'jajarkot',
    'jhapa',
    'jumla',
    'kailali',
    'kalikot',
    'kanchanpur',
    'kapilvastu',
    'kaski',
    'kathmandu',
    'kavrepalanchok',
    'khotang',
    'lalitpur',
    'lamjung',
    'mahottari',
    'makwanpur',
    'manang',
    'morang',
    'mugu',
    'mustang',
    'myagdi',
    'nawalparasi',
    'nuwakot',
    'okhaldhunga',
    'palpa',
    'panchthar',
    'parbat',
    'parsa',
    'pyuthan',
    'ramechhap',
    'rasuwa',
    'rautahat',
    'rolpa',
    'rukum',
    'rupandehi',
    'salyan',
    'sankhuwasabha',
    'saptari',
    'sarlahi',
    'sindhuli',
    'sindhupalchok',
    'siraha',
    'solukhumbu',
    'sunsari',
    'surkhet',
    'syangja',
    'tanahu',
    'taplejung',
    'terhathum',
    'udayapur',
  ]),
  address: sample([
    'bagmati nagarpalika, sarlahi',
    'sunpaani-2',
    'kirtipur-9',
    'pokhara-3',
    'lalitpur-5',
  ]),
  death_place: sample([
    'norvic hospital',
    'kirtipur hospital',
    'shukra raj hospital',
  ]),
  commorbidity: sample([
    'diabetes',
    'hypertension',
    'asthma',
    'cancer',
    'tuberculosis',
    'heart disease',
    'liver disease',
    'kidney disease',
    'lung disease',
    'pneumonia',
    'respiratory disease',
    'skin disease',
    'other',
  ]),
  remarks: faker.lorem.sentence(),
}));

export default covidDeath;
