// export { default as AppConversionRates } from './AppConversionRates';
// export { default as AppCurrentSubject } from './AppCurrentSubject';
export { default as CovidDeaths } from './CovidDeaths';
export { default as CovidRecovered } from './CovidRecovered';
export { default as DataLocationPositive } from './DataLocationPositive';
export { default as DataLocationDeath } from './DataLocationDeath';
export { default as NewCovidPositive } from './NewCovidPositive';
export { default as TotalDataChart } from './TotalDataChart';
export { default as AppOrderTimeline } from './AppOrderTimeline';
//export { default as AppTasks } from './AppTasks';
export { default as CovidPositiveBar} from './CovidPositiveBar';
export {default as CovidNewCases} from './CovidNewCases';
export { default as DistrictsReportingNewCases} from './DistrictsReportingNewCases';
export { default as NumberofActiveCase } from './NumberofActiveCase';
export { default as RollingDaysTotal } from './RollingDaysTotal';
export { default as DailyTestsAndPositivityRate } from './DailyTestsAndPositivityRate';
export { default as DailyPositiveCases } from './DailyPositiveCases';
export { default as DailyNewPositiveAndRecoveredCases } from './DailyNewPositiveAndRecoveredCases';
export {default as WeeklyTestPositiveCases} from './WeeklyTestPositiveCases';
export { default as EstimatedAndReported } from './EstimatedAndReported';
export { default as NewCasesCard } from './NewCasesCard';
export {default as NewActiveCasesCard } from './NewActiveCasesCard';
export { default as PredictiveValues} from './PredictiveValues';
export { default as CovidByAge } from './CovidByAge';
export { default as SexAndAgeComposition } from './SexAndAgeComposition';
export {default as AgeSpecificPrevalence} from './AgeSpecificPrevalence';
export { default as KTMValleyandOutsideValley} from './KTMValleyandOutsideValley';
export {default as ActiveRecoveredDeathProvince} from './ActiveRecoveredDeathProvince';
export {default as SARILines} from './SARILines';
export { default as DailyCriticalCases} from './DailyCriticalCases';
export { default as DeathsBasedOnDate } from './DeathsBasedOnDate';
export { default as DeathsBasedOnDateofReport } from './DeathsBasedOnDateofReport';
export { default as RollingDeathsDaysTotal } from './RollingDeathsDaysTotal';
export { default as DeathsBySexProvince } from './DeathsBySexProvince';